blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/JeremiahBoothe/JeremiahBoothe.github.io.git
    about: Please post your support questions in the Discussions section.